# Uso de DataFrame en Pandas
##### Maestría en Inteligencia Artificial Aplicada · Herramientas para IA · Semana 2

Datos académicos **ficticios** para experimentación. Ejecute las celdas en orden.

In [1]:
import pandas as pd
import numpy as np

## 1. Leer un archivo CSV
Como en los ejemplos anteriores: leemos desde `data/` y observamos directamente el DataFrame.

In [2]:
mi_df = pd.read_csv('data/rendimiento_100.csv')
mi_df

,id_estudiante,carrera,modalidad,edad,nota_final,horas_estudio,asistencia,aprobado,comentario
0,1,Tecnologías de la Información,En línea,38,48.1,7,69,0.0,No entiendo algunos temas y necesito más ejemp...
1,2,Computación,En línea,25,59.7,12,58,0.0,Me cuesta seguir las explicaciones y practicar.
2,3,Computación,Presencial,41,79.0,15,86,1.0,Me falta tiempo para repasar los conceptos de ...
3,4,Redes,Presencial,45,68.1,8,68,0.0,Necesito apoyo para organizar mi tiempo de est...
4,5,Computación,En línea,28,83.9,17,67,1.0,Las explicaciones son claras y puedo resolver ...
...,...,...,...,...,...,...,...,...,...
95,96,Tecnologías de la Información,Presencial,23,79.9,19,53,1.0,Me falta tiempo para repasar los conceptos de ...
96,97,Tecnologías de la Información,En línea,31,100.0,15,77,1.0,Comprendo las actividades y disfruto practicar...
97,98,Analítica de Datos,Presencial,20,72.2,15,72,1.0,Tengo dudas en ciertos ejercicios y necesito o...
98,99,Tecnologías de la Información,En línea,28,100.0,18,100,1.0,Comprendo las actividades y disfruto practicar...
99,100,Tecnologías de la Información,En línea,23,89.7,20,79,1.0,Comprendo las actividades y disfruto practicar...

In [3]:
mi_df.head()

,id_estudiante,carrera,modalidad,edad,nota_final,horas_estudio,asistencia,aprobado,comentario
0,1,Tecnologías de la Información,En línea,38,48.1,7,69,0.0,No entiendo algunos temas y necesito más ejemp...
1,2,Computación,En línea,25,59.7,12,58,0.0,Me cuesta seguir las explicaciones y practicar.
2,3,Computación,Presencial,41,79.0,15,86,1.0,Me falta tiempo para repasar los conceptos de ...
3,4,Redes,Presencial,45,68.1,8,68,0.0,Necesito apoyo para organizar mi tiempo de est...
4,5,Computación,En línea,28,83.9,17,67,1.0,Las explicaciones son claras y puedo resolver ...

In [4]:
mi_df.shape

(100, 9)

In [5]:
mi_df.columns

Index(['id_estudiante', 'carrera', 'modalidad', 'edad', 'nota_final',
       'horas_estudio', 'asistencia', 'aprobado', 'comentario'],
      dtype='str')

In [6]:
mi_df.dtypes

id_estudiante      int64
carrera              str
modalidad            str
edad               int64
nota_final       float64
horas_estudio      int64
asistencia         int64
aprobado         float64
comentario           str
dtype: object

In [7]:
mi_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id_estudiante  100 non-null    int64
 1   carrera        100 non-null    str
 2   modalidad      100 non-null    str
 3   edad           100 non-null    int64
 4   nota_final     97 non-null     float64
 5   horas_estudio  100 non-null    int64
 6   asistencia     100 non-null    int64
 7   aprobado       97 non-null     float64
 8   comentario     100 non-null    str
dtypes: float64(2), int64(4), str(3)
memory usage: 7.2 KB

## 2. Explorar y seleccionar

In [8]:
mi_df.describe()

,id_estudiante,edad,nota_final,horas_estudio,asistencia,aprobado
count,100.000000,100.000000,97.000000,100.000000,100.000000,97.000000
mean,50.500000,31.010000,74.628866,11.480000,69.230000,0.608247
std,29.011492,8.159391,14.785649,6.036053,15.445476,0.490678
min,1.000000,18.000000,33.900000,1.000000,48.000000,0.000000
25%,25.750000,23.750000,64.700000,7.000000,55.000000,0.000000
50%,50.500000,31.000000,76.100000,12.000000,68.000000,1.000000
75%,75.250000,39.000000,87.300000,17.000000,82.000000,1.000000
max,100.000000,45.000000,100.000000,20.000000,100.000000,1.000000

In [9]:
mi_df[['carrera', 'nota_final', 'horas_estudio']]

                          carrera  nota_final  horas_estudio
0   Tecnologías de la Información        48.1              7
1                     Computación        59.7             12
2                     Computación        79.0             15
3                           Redes        68.1              8
4                     Computación        83.9             17
..                            ...         ...            ...
95  Tecnologías de la Información        79.9             19
96  Tecnologías de la Información       100.0             15
97             Analítica de Datos        72.2             15
98  Tecnologías de la Información       100.0             18
99  Tecnologías de la Información        89.7             20

[100 rows x 3 columns]

In [10]:
mi_df[mi_df['nota_final'] >= 80]

,id_estudiante,carrera,modalidad,edad,nota_final,horas_estudio,asistencia,aprobado,comentario
4,5,Computación,En línea,28,83.9,17,67,1.0,Las explicaciones son claras y puedo resolver ...
7,8,Computación,Presencial,40,88.0,20,93,1.0,Comprendo las actividades y disfruto practicar...
12,13,Tecnologías de la Información,Presencial,42,87.8,11,98,1.0,Estudio con regularidad y me ayuda practicar c...
17,18,Tecnologías de la Información,Presencial,31,86.0,20,69,1.0,Las explicaciones son claras y puedo resolver ...
20,21,Tecnologías de la Información,En línea,40,91.3,18,52,1.0,Me siento motivado y organizo bien mis activid...
26,27,Tecnologías de la Información,En línea,26,90.9,4,58,1.0,Estudio con regularidad y me ayuda practicar c...
27,28,Computación,En línea,20,92.3,18,78,1.0,Estudio con regularidad y me ayuda practicar c...
30,31,Computación,En línea,36,84.3,18,55,1.0,Las explicaciones son claras y puedo resolver ...
32,33,Computación,Presencial,29,96.1,15,60,1.0,Las explicaciones son claras y puedo resolver ...
34,35,Analítica de Datos,Presencial,37,96.5,16,92,1.0,Las explicaciones son claras y puedo resolver ...
35,36,Redes,En línea,40,97.7,20,68,1.0,Estudio con regularidad y me ayuda practicar c...
36,37,Computación,Presencial,41,87.4,19,81,1.0,Comprendo las actividades y disfruto practicar...
42,43,Redes,Presencial,18,89.9,13,82,1.0,Me siento motivado y organizo bien mis activid...
43,44,Redes,Presencial,37,89.0,9,80,1.0,Comprendo las actividades y disfruto practicar...
46,47,Tecnologías de la Información,En línea,33,85.6,15,51,1.0,Las explicaciones son claras y puedo resolver ...
47,48,Computación,En línea,39,84.8,15,96,1.0,Me siento motivado y organizo bien mis activid...
50,51,Computación,En línea,41,88.5,17,84,1.0,Comprendo las actividades y disfruto practicar...
53,54,Tecnologías de la Información,En línea,41,81.6,17,81,1.0,Las explicaciones son claras y puedo resolver ...
55,56,Computación,En línea,45,89.8,11,81,1.0,Estudio con regularidad y me ayuda practicar c...
57,58,Analítica de Datos,Presencial,39,91.8,17,60,1.0,Estudio con regularidad y me ayuda practicar c...
58,59,Analítica de Datos,Presencial,29,87.5,20,51,1.0,Estudio con regularidad y me ayuda practicar c...
59,60,Computación,Presencial,26,87.3,19,96,1.0,Me siento motivado y organizo bien mis activid...
60,61,Tecnologías de la Información,En línea,21,100.0,19,69,1.0,Las explicaciones son claras y puedo resolver ...
63,64,Analítica de Datos,Presencial,36,87.6,11,60,1.0,Las explicaciones son claras y puedo resolver ...
66,67,Redes,Presencial,29,96.5,19,66,1.0,Estudio con regularidad y me ayuda practicar c...
70,71,Redes,Presencial,20,82.6,18,50,1.0,Estudio con regularidad y me ayuda practicar c...
75,76,Analítica de Datos,En línea,25,94.8,12,73,1.0,Comprendo las actividades y disfruto practicar...
76,77,Computación,En línea,42,91.0,7,90,1.0,Comprendo las actividades y disfruto practicar...
80,81,Analítica de Datos,Presencial,40,85.1,19,68,1.0,Las explicaciones son claras y puedo resolver ...
81,82,Computación,En línea,22,90.0,18,83,1.0,Me siento motivado y organizo bien mis activid...
83,84,Analítica de Datos,Presencial,43,86.9,17,82,1.0,Las explicaciones son claras y puedo resolver ...
86,87,Analítica de Datos,En línea,19,80.2,12,59,1.0,Me siento motivado y organizo bien mis activid...
96,97,Tecnologías de la Información,En línea,31,100.0,15,77,1.0,Comprendo las actividades y disfruto practicar...
98,99,Tecnologías de la Información,En línea,28,100.0,18,100,1.0,Comprendo las actividades y disfruto practicar...
99,100,Tecnologías de la Información,En línea,23,89.7,20,79,1.0,Comprendo las actividades y disfruto practicar...

In [11]:
mi_df[(mi_df['asistencia'] >= 80) & (mi_df['horas_estudio'] >= 10)]

,id_estudiante,carrera,modalidad,edad,nota_final,horas_estudio,asistencia,aprobado,comentario
2,3,Computación,Presencial,41,79.0,15,86,1.0,Me falta tiempo para repasar los conceptos de ...
7,8,Computación,Presencial,40,88.0,20,93,1.0,Comprendo las actividades y disfruto practicar...
12,13,Tecnologías de la Información,Presencial,42,87.8,11,98,1.0,Estudio con regularidad y me ayuda practicar c...
29,30,Computación,Presencial,44,65.8,11,82,0.0,No entiendo algunos temas y necesito más ejemp...
34,35,Analítica de Datos,Presencial,37,96.5,16,92,1.0,Las explicaciones son claras y puedo resolver ...
36,37,Computación,Presencial,41,87.4,19,81,1.0,Comprendo las actividades y disfruto practicar...
42,43,Redes,Presencial,18,89.9,13,82,1.0,Me siento motivado y organizo bien mis activid...
47,48,Computación,En línea,39,84.8,15,96,1.0,Me siento motivado y organizo bien mis activid...
50,51,Computación,En línea,41,88.5,17,84,1.0,Comprendo las actividades y disfruto practicar...
53,54,Tecnologías de la Información,En línea,41,81.6,17,81,1.0,Las explicaciones son claras y puedo resolver ...
55,56,Computación,En línea,45,89.8,11,81,1.0,Estudio con regularidad y me ayuda practicar c...
59,60,Computación,Presencial,26,87.3,19,96,1.0,Me siento motivado y organizo bien mis activid...
73,74,Tecnologías de la Información,En línea,31,76.2,13,96,1.0,Comprendo algunos temas pero necesito practica...
81,82,Computación,En línea,22,90.0,18,83,1.0,Me siento motivado y organizo bien mis activid...
83,84,Analítica de Datos,Presencial,43,86.9,17,82,1.0,Las explicaciones son claras y puedo resolver ...
98,99,Tecnologías de la Información,En línea,28,100.0,18,100,1.0,Comprendo las actividades y disfruto practicar...

In [12]:
mi_df.sort_values('nota_final', ascending=False).head(10)

,id_estudiante,carrera,modalidad,edad,nota_final,horas_estudio,asistencia,aprobado,comentario
60,61,Tecnologías de la Información,En línea,21,100.0,19,69,1.0,Las explicaciones son claras y puedo resolver ...
98,99,Tecnologías de la Información,En línea,28,100.0,18,100,1.0,Comprendo las actividades y disfruto practicar...
96,97,Tecnologías de la Información,En línea,31,100.0,15,77,1.0,Comprendo las actividades y disfruto practicar...
35,36,Redes,En línea,40,97.7,20,68,1.0,Estudio con regularidad y me ayuda practicar c...
66,67,Redes,Presencial,29,96.5,19,66,1.0,Estudio con regularidad y me ayuda practicar c...
34,35,Analítica de Datos,Presencial,37,96.5,16,92,1.0,Las explicaciones son claras y puedo resolver ...
32,33,Computación,Presencial,29,96.1,15,60,1.0,Las explicaciones son claras y puedo resolver ...
75,76,Analítica de Datos,En línea,25,94.8,12,73,1.0,Comprendo las actividades y disfruto practicar...
27,28,Computación,En línea,20,92.3,18,78,1.0,Estudio con regularidad y me ayuda practicar c...
57,58,Analítica de Datos,Presencial,39,91.8,17,60,1.0,Estudio con regularidad y me ayuda practicar c...

## 3. Datos faltantes
No conviene reemplazar automáticamente las notas desconocidas por cero: cambiaríamos el significado de los datos.

In [13]:
mi_df.isna().sum()

id_estudiante    0
carrera          0
modalidad        0
edad             0
nota_final       3
horas_estudio    0
asistencia       0
aprobado         3
comentario       0
dtype: int64

In [14]:
# Elimina las filas que tienen valores nulos (NaN) en la columna nota_final.
mi_df.dropna(subset=['nota_final'])

,id_estudiante,carrera,modalidad,edad,nota_final,horas_estudio,asistencia,aprobado,comentario
0,1,Tecnologías de la Información,En línea,38,48.1,7,69,0.0,No entiendo algunos temas y necesito más ejemp...
1,2,Computación,En línea,25,59.7,12,58,0.0,Me cuesta seguir las explicaciones y practicar.
2,3,Computación,Presencial,41,79.0,15,86,1.0,Me falta tiempo para repasar los conceptos de ...
3,4,Redes,Presencial,45,68.1,8,68,0.0,Necesito apoyo para organizar mi tiempo de est...
4,5,Computación,En línea,28,83.9,17,67,1.0,Las explicaciones son claras y puedo resolver ...
...,...,...,...,...,...,...,...,...,...
95,96,Tecnologías de la Información,Presencial,23,79.9,19,53,1.0,Me falta tiempo para repasar los conceptos de ...
96,97,Tecnologías de la Información,En línea,31,100.0,15,77,1.0,Comprendo las actividades y disfruto practicar...
97,98,Analítica de Datos,Presencial,20,72.2,15,72,1.0,Tengo dudas en ciertos ejercicios y necesito o...
98,99,Tecnologías de la Información,En línea,28,100.0,18,100,1.0,Comprendo las actividades y disfruto practicar...
99,100,Tecnologías de la Información,En línea,23,89.7,20,79,1.0,Comprendo las actividades y disfruto practicar...

## 4. Resumir y transformar

In [15]:
mi_df.groupby('carrera')['nota_final'].mean()

carrera
Analítica de Datos               74.290000
Computación                      76.814286
Redes                            73.045455
Tecnologías de la Información    73.903704
Name: nota_final, dtype: float64

In [16]:
mi_df.groupby(['carrera', 'modalidad'])['nota_final'].agg(['count', 'mean', 'min', 'max']).round(2)

                                          count   mean   min    max
carrera                       modalidad
Analítica de Datos            En línea        7  75.77  54.7   94.8
                              Presencial     13  73.49  33.9   96.5
Computación                   En línea       14  80.46  59.7   92.3
                              Presencial     14  73.17  48.6   96.1
Redes                         En línea       10  70.06  60.4   97.7
                              Presencial     12  75.53  62.8   96.5
Tecnologías de la Información En línea       18  75.12  35.1  100.0
                              Presencial      9  71.48  53.1   87.8

In [17]:
mi_df['nivel_asistencia'] = np.where(mi_df['asistencia'] >= 80, 'Alta', 'Por revisar')
mi_df.head()

,id_estudiante,carrera,modalidad,edad,nota_final,horas_estudio,asistencia,aprobado,comentario,nivel_asistencia
0,1,Tecnologías de la Información,En línea,38,48.1,7,69,0.0,No entiendo algunos temas y necesito más ejemp...,Por revisar
1,2,Computación,En línea,25,59.7,12,58,0.0,Me cuesta seguir las explicaciones y practicar.,Por revisar
2,3,Computación,Presencial,41,79.0,15,86,1.0,Me falta tiempo para repasar los conceptos de ...,Alta
3,4,Redes,Presencial,45,68.1,8,68,0.0,Necesito apoyo para organizar mi tiempo de est...,Por revisar
4,5,Computación,En línea,28,83.9,17,67,1.0,Las explicaciones son claras y puedo resolver ...,Por revisar

## 5. Cambiar el tamaño del conjunto

In [18]:
df_1000 = pd.read_csv('data/rendimiento_1000.csv')
df_10000 = pd.read_csv('data/rendimiento_10000.csv')
print(mi_df.shape, df_1000.shape, df_10000.shape)

(100, 10) (1000, 9) (10000, 9)