# Uso de DataFrame en Pandas y Polars
##### Maestría en Inteligencia Artificial Aplicada · Herramientas para IA · Semana 2

Datos académicos **ficticios** para experimentación. Ejecute las celdas en orden.

In [1]:
import pandas as pd
import polars as pl
from time import perf_counter

## 1. Cargar exactamente el mismo archivo

In [2]:
mi_df = pd.read_csv('data/rendimiento_100.csv')
mi_df

,id_estudiante,carrera,modalidad,edad,nota_final,horas_estudio,asistencia,aprobado,comentario
0,1,Tecnologías de la Información,En línea,38,48.1,7,69,0.0,No entiendo algunos temas y necesito más ejemp...
1,2,Computación,En línea,25,59.7,12,58,0.0,Me cuesta seguir las explicaciones y practicar.
2,3,Computación,Presencial,41,79.0,15,86,1.0,Me falta tiempo para repasar los conceptos de ...
3,4,Redes,Presencial,45,68.1,8,68,0.0,Necesito apoyo para organizar mi tiempo de est...
4,5,Computación,En línea,28,83.9,17,67,1.0,Las explicaciones son claras y puedo resolver ...
...,...,...,...,...,...,...,...,...,...
95,96,Tecnologías de la Información,Presencial,23,79.9,19,53,1.0,Me falta tiempo para repasar los conceptos de ...
96,97,Tecnologías de la Información,En línea,31,100.0,15,77,1.0,Comprendo las actividades y disfruto practicar...
97,98,Analítica de Datos,Presencial,20,72.2,15,72,1.0,Tengo dudas en ciertos ejercicios y necesito o...
98,99,Tecnologías de la Información,En línea,28,100.0,18,100,1.0,Comprendo las actividades y disfruto practicar...
99,100,Tecnologías de la Información,En línea,23,89.7,20,79,1.0,Comprendo las actividades y disfruto practicar...

In [3]:
df_polars = pl.read_csv('data/rendimiento_100.csv')
df_polars

shape: (100, 9)
┌────────────┬────────────┬────────────┬──────┬───┬────────────┬────────────┬──────────┬───────────┐
│ id_estudia ┆ carrera    ┆ modalidad  ┆ edad ┆ … ┆ horas_estu ┆ asistencia ┆ aprobado ┆ comentari │
│ nte        ┆ ---        ┆ ---        ┆ ---  ┆   ┆ dio        ┆ ---        ┆ ---      ┆ o         │
│ ---        ┆ str        ┆ str        ┆ i64  ┆   ┆ ---        ┆ i64        ┆ i64      ┆ ---       │
│ i64        ┆            ┆            ┆      ┆   ┆ i64        ┆            ┆          ┆ str       │
╞════════════╪════════════╪════════════╪══════╪═══╪════════════╪════════════╪══════════╪═══════════╡
│ 1          ┆ Tecnología ┆ En línea   ┆ 38   ┆ … ┆ 7          ┆ 69         ┆ 0        ┆ No        │
│            ┆ s de la    ┆            ┆      ┆   ┆            ┆            ┆          ┆ entiendo  │
│            ┆ Informació ┆            ┆      ┆   ┆            ┆            ┆          ┆ algunos   │
│            ┆ n          ┆            ┆      ┆   ┆            ┆            ┆          ┆ temas y   │
│            ┆            ┆            ┆      ┆   ┆            ┆            ┆          ┆ ne…       │
│ 2          ┆ Computació ┆ En línea   ┆ 25   ┆ … ┆ 12         ┆ 58         ┆ 0        ┆ Me cuesta │
│            ┆ n          ┆            ┆      ┆   ┆            ┆            ┆          ┆ seguir    │
│            ┆            ┆            ┆      ┆   ┆            ┆            ┆          ┆ las expli │
│            ┆            ┆            ┆      ┆   ┆            ┆            ┆          ┆ caci…     │
│ 3          ┆ Computació ┆ Presencial ┆ 41   ┆ … ┆ 15         ┆ 86         ┆ 1        ┆ Me falta  │
│            ┆ n          ┆            ┆      ┆   ┆            ┆            ┆          ┆ tiempo    │
│            ┆            ┆            ┆      ┆   ┆            ┆            ┆          ┆ para      │
│            ┆            ┆            ┆      ┆   ┆            ┆            ┆          ┆ repasar   │
│            ┆            ┆            ┆      ┆   ┆            ┆            ┆          ┆ l…        │
│ 4          ┆ Redes      ┆ Presencial ┆ 45   ┆ … ┆ 8          ┆ 68         ┆ 0        ┆ Necesito  │
│            ┆            ┆            ┆      ┆   ┆            ┆            ┆          ┆ apoyo     │
│            ┆            ┆            ┆      ┆   ┆            ┆            ┆          ┆ para      │
│            ┆            ┆            ┆      ┆   ┆            ┆            ┆          ┆ organizar │
│            ┆            ┆            ┆      ┆   ┆            ┆            ┆          ┆ …         │
│ 5          ┆ Computació ┆ En línea   ┆ 28   ┆ … ┆ 17         ┆ 67         ┆ 1        ┆ Las expli │
│            ┆ n          ┆            ┆      ┆   ┆            ┆            ┆          ┆ caciones  │
│            ┆            ┆            ┆      ┆   ┆            ┆            ┆          ┆ son       │
│            ┆            ┆            ┆      ┆   ┆            ┆            ┆          ┆ claras y… │
│ …          ┆ …          ┆ …          ┆ …    ┆ … ┆ …          ┆ …          ┆ …        ┆ …         │
│ 96         ┆ Tecnología ┆ Presencial ┆ 23   ┆ … ┆ 19         ┆ 53         ┆ 1        ┆ Me falta  │
│            ┆ s de la    ┆            ┆      ┆   ┆            ┆            ┆          ┆ tiempo    │
│            ┆ Informació ┆            ┆      ┆   ┆            ┆            ┆          ┆ para      │
│            ┆ n          ┆            ┆      ┆   ┆            ┆            ┆          ┆ repasar   │
│            ┆            ┆            ┆      ┆   ┆            ┆            ┆          ┆ l…        │
│ 97         ┆ Tecnología ┆ En línea   ┆ 31   ┆ … ┆ 15         ┆ 77         ┆ 1        ┆ Comprendo │
│            ┆ s de la    ┆            ┆      ┆   ┆            ┆            ┆          ┆ las activ │
│            ┆ Informació ┆            ┆      ┆   ┆            ┆            ┆          ┆ idades y  │
│            ┆ n          ┆            ┆      ┆   ┆            ┆            ┆          ┆ di…       │
│ 98         ┆ Analítica  ┆ Presencial ┆ 20   ┆ … ┆ 15         ┆ 72         ┆ 1        ┆ Tengo     │
│            ┆ de Datos   ┆            ┆      ┆   ┆            ┆            ┆          ┆ dudas en  │
│            ┆            ┆            ┆      ┆   ┆            ┆            ┆          ┆ ciertos   │
│            ┆            ┆            ┆      ┆   ┆            ┆            ┆          ┆ ejercic…  │
│ 99         ┆ Tecnología ┆ En línea   ┆ 28   ┆ … ┆ 18         ┆ 100        ┆ 1        ┆ Comprendo │
│            ┆ s de la    ┆            ┆      ┆   ┆            ┆            ┆          ┆ las activ │
│            ┆ Informació ┆            ┆      ┆   ┆            ┆            ┆          ┆ idades y  │
│            ┆ n          ┆            ┆      ┆   ┆            ┆            ┆          ┆ di…       │
│ 100        ┆ Tecnología ┆ En línea   ┆ 23   ┆ … ┆ 20         ┆ 79         ┆ 1        ┆ Comprendo │
│            ┆ s de la    ┆            ┆      ┆   ┆            ┆            ┆          ┆ las activ │
│            ┆ Informació ┆            ┆      ┆   ┆            ┆            ┆          ┆ idades y  │
│            ┆ n          ┆            ┆      ┆   ┆            ┆            ┆          ┆ di…       │
└────────────┴────────────┴────────────┴──────┴───┴────────────┴────────────┴──────────┴───────────┘

In [4]:
mi_df.head()

,id_estudiante,carrera,modalidad,edad,nota_final,horas_estudio,asistencia,aprobado,comentario
0,1,Tecnologías de la Información,En línea,38,48.1,7,69,0.0,No entiendo algunos temas y necesito más ejemp...
1,2,Computación,En línea,25,59.7,12,58,0.0,Me cuesta seguir las explicaciones y practicar.
2,3,Computación,Presencial,41,79.0,15,86,1.0,Me falta tiempo para repasar los conceptos de ...
3,4,Redes,Presencial,45,68.1,8,68,0.0,Necesito apoyo para organizar mi tiempo de est...
4,5,Computación,En línea,28,83.9,17,67,1.0,Las explicaciones son claras y puedo resolver ...

In [5]:
df_polars.head()

shape: (5, 9)
┌────────────┬────────────┬────────────┬──────┬───┬────────────┬────────────┬──────────┬───────────┐
│ id_estudia ┆ carrera    ┆ modalidad  ┆ edad ┆ … ┆ horas_estu ┆ asistencia ┆ aprobado ┆ comentari │
│ nte        ┆ ---        ┆ ---        ┆ ---  ┆   ┆ dio        ┆ ---        ┆ ---      ┆ o         │
│ ---        ┆ str        ┆ str        ┆ i64  ┆   ┆ ---        ┆ i64        ┆ i64      ┆ ---       │
│ i64        ┆            ┆            ┆      ┆   ┆ i64        ┆            ┆          ┆ str       │
╞════════════╪════════════╪════════════╪══════╪═══╪════════════╪════════════╪══════════╪═══════════╡
│ 1          ┆ Tecnología ┆ En línea   ┆ 38   ┆ … ┆ 7          ┆ 69         ┆ 0        ┆ No        │
│            ┆ s de la    ┆            ┆      ┆   ┆            ┆            ┆          ┆ entiendo  │
│            ┆ Informació ┆            ┆      ┆   ┆            ┆            ┆          ┆ algunos   │
│            ┆ n          ┆            ┆      ┆   ┆            ┆            ┆          ┆ temas y   │
│            ┆            ┆            ┆      ┆   ┆            ┆            ┆          ┆ ne…       │
│ 2          ┆ Computació ┆ En línea   ┆ 25   ┆ … ┆ 12         ┆ 58         ┆ 0        ┆ Me cuesta │
│            ┆ n          ┆            ┆      ┆   ┆            ┆            ┆          ┆ seguir    │
│            ┆            ┆            ┆      ┆   ┆            ┆            ┆          ┆ las expli │
│            ┆            ┆            ┆      ┆   ┆            ┆            ┆          ┆ caci…     │
│ 3          ┆ Computació ┆ Presencial ┆ 41   ┆ … ┆ 15         ┆ 86         ┆ 1        ┆ Me falta  │
│            ┆ n          ┆            ┆      ┆   ┆            ┆            ┆          ┆ tiempo    │
│            ┆            ┆            ┆      ┆   ┆            ┆            ┆          ┆ para      │
│            ┆            ┆            ┆      ┆   ┆            ┆            ┆          ┆ repasar   │
│            ┆            ┆            ┆      ┆   ┆            ┆            ┆          ┆ l…        │
│ 4          ┆ Redes      ┆ Presencial ┆ 45   ┆ … ┆ 8          ┆ 68         ┆ 0        ┆ Necesito  │
│            ┆            ┆            ┆      ┆   ┆            ┆            ┆          ┆ apoyo     │
│            ┆            ┆            ┆      ┆   ┆            ┆            ┆          ┆ para      │
│            ┆            ┆            ┆      ┆   ┆            ┆            ┆          ┆ organizar │
│            ┆            ┆            ┆      ┆   ┆            ┆            ┆          ┆ …         │
│ 5          ┆ Computació ┆ En línea   ┆ 28   ┆ … ┆ 17         ┆ 67         ┆ 1        ┆ Las expli │
│            ┆ n          ┆            ┆      ┆   ┆            ┆            ┆          ┆ caciones  │
│            ┆            ┆            ┆      ┆   ┆            ┆            ┆          ┆ son       │
│            ┆            ┆            ┆      ┆   ┆            ┆            ┆          ┆ claras y… │
└────────────┴────────────┴────────────┴──────┴───┴────────────┴────────────┴──────────┴───────────┘

In [6]:
mi_df.dtypes

id_estudiante      int64
carrera              str
modalidad            str
edad               int64
nota_final       float64
horas_estudio      int64
asistencia         int64
aprobado         float64
comentario           str
dtype: object

In [7]:
df_polars.dtypes

[Int64, String, String, Int64, Float64, Int64, Int64, Int64, String]

## 2. Seleccionar, filtrar y ordenar

In [8]:
mi_df[['carrera', 'nota_final']]

                          carrera  nota_final
0   Tecnologías de la Información        48.1
1                     Computación        59.7
2                     Computación        79.0
3                           Redes        68.1
4                     Computación        83.9
..                            ...         ...
95  Tecnologías de la Información        79.9
96  Tecnologías de la Información       100.0
97             Analítica de Datos        72.2
98  Tecnologías de la Información       100.0
99  Tecnologías de la Información        89.7

[100 rows x 2 columns]

In [9]:
df_polars[['carrera', 'nota_final']]

shape: (100, 2)
┌───────────────────────────────┬────────────┐
│ carrera                       ┆ nota_final │
│ ---                           ┆ ---        │
│ str                           ┆ f64        │
╞═══════════════════════════════╪════════════╡
│ Tecnologías de la Información ┆ 48.1       │
│ Computación                   ┆ 59.7       │
│ Computación                   ┆ 79.0       │
│ Redes                         ┆ 68.1       │
│ Computación                   ┆ 83.9       │
│ …                             ┆ …          │
│ Tecnologías de la Información ┆ 79.9       │
│ Tecnologías de la Información ┆ 100.0      │
│ Analítica de Datos            ┆ 72.2       │
│ Tecnologías de la Información ┆ 100.0      │
│ Tecnologías de la Información ┆ 89.7       │
└───────────────────────────────┴────────────┘

In [10]:
mi_df[mi_df['nota_final'] >= 80]

,id_estudiante,carrera,modalidad,edad,nota_final,horas_estudio,asistencia,aprobado,comentario
4,5,Computación,En línea,28,83.9,17,67,1.0,Las explicaciones son claras y puedo resolver ...
7,8,Computación,Presencial,40,88.0,20,93,1.0,Comprendo las actividades y disfruto practicar...
12,13,Tecnologías de la Información,Presencial,42,87.8,11,98,1.0,Estudio con regularidad y me ayuda practicar c...
17,18,Tecnologías de la Información,Presencial,31,86.0,20,69,1.0,Las explicaciones son claras y puedo resolver ...
20,21,Tecnologías de la Información,En línea,40,91.3,18,52,1.0,Me siento motivado y organizo bien mis activid...
26,27,Tecnologías de la Información,En línea,26,90.9,4,58,1.0,Estudio con regularidad y me ayuda practicar c...
27,28,Computación,En línea,20,92.3,18,78,1.0,Estudio con regularidad y me ayuda practicar c...
30,31,Computación,En línea,36,84.3,18,55,1.0,Las explicaciones son claras y puedo resolver ...
32,33,Computación,Presencial,29,96.1,15,60,1.0,Las explicaciones son claras y puedo resolver ...
34,35,Analítica de Datos,Presencial,37,96.5,16,92,1.0,Las explicaciones son claras y puedo resolver ...
35,36,Redes,En línea,40,97.7,20,68,1.0,Estudio con regularidad y me ayuda practicar c...
36,37,Computación,Presencial,41,87.4,19,81,1.0,Comprendo las actividades y disfruto practicar...
42,43,Redes,Presencial,18,89.9,13,82,1.0,Me siento motivado y organizo bien mis activid...
43,44,Redes,Presencial,37,89.0,9,80,1.0,Comprendo las actividades y disfruto practicar...
46,47,Tecnologías de la Información,En línea,33,85.6,15,51,1.0,Las explicaciones son claras y puedo resolver ...
47,48,Computación,En línea,39,84.8,15,96,1.0,Me siento motivado y organizo bien mis activid...
50,51,Computación,En línea,41,88.5,17,84,1.0,Comprendo las actividades y disfruto practicar...
53,54,Tecnologías de la Información,En línea,41,81.6,17,81,1.0,Las explicaciones son claras y puedo resolver ...
55,56,Computación,En línea,45,89.8,11,81,1.0,Estudio con regularidad y me ayuda practicar c...
57,58,Analítica de Datos,Presencial,39,91.8,17,60,1.0,Estudio con regularidad y me ayuda practicar c...
58,59,Analítica de Datos,Presencial,29,87.5,20,51,1.0,Estudio con regularidad y me ayuda practicar c...
59,60,Computación,Presencial,26,87.3,19,96,1.0,Me siento motivado y organizo bien mis activid...
60,61,Tecnologías de la Información,En línea,21,100.0,19,69,1.0,Las explicaciones son claras y puedo resolver ...
63,64,Analítica de Datos,Presencial,36,87.6,11,60,1.0,Las explicaciones son claras y puedo resolver ...
66,67,Redes,Presencial,29,96.5,19,66,1.0,Estudio con regularidad y me ayuda practicar c...
70,71,Redes,Presencial,20,82.6,18,50,1.0,Estudio con regularidad y me ayuda practicar c...
75,76,Analítica de Datos,En línea,25,94.8,12,73,1.0,Comprendo las actividades y disfruto practicar...
76,77,Computación,En línea,42,91.0,7,90,1.0,Comprendo las actividades y disfruto practicar...
80,81,Analítica de Datos,Presencial,40,85.1,19,68,1.0,Las explicaciones son claras y puedo resolver ...
81,82,Computación,En línea,22,90.0,18,83,1.0,Me siento motivado y organizo bien mis activid...
83,84,Analítica de Datos,Presencial,43,86.9,17,82,1.0,Las explicaciones son claras y puedo resolver ...
86,87,Analítica de Datos,En línea,19,80.2,12,59,1.0,Me siento motivado y organizo bien mis activid...
96,97,Tecnologías de la Información,En línea,31,100.0,15,77,1.0,Comprendo las actividades y disfruto practicar...
98,99,Tecnologías de la Información,En línea,28,100.0,18,100,1.0,Comprendo las actividades y disfruto practicar...
99,100,Tecnologías de la Información,En línea,23,89.7,20,79,1.0,Comprendo las actividades y disfruto practicar...

In [11]:
df_polars.filter(pl.col("nota_final") >= 80)

shape: (35, 9)
┌────────────┬────────────┬────────────┬──────┬───┬────────────┬────────────┬──────────┬───────────┐
│ id_estudia ┆ carrera    ┆ modalidad  ┆ edad ┆ … ┆ horas_estu ┆ asistencia ┆ aprobado ┆ comentari │
│ nte        ┆ ---        ┆ ---        ┆ ---  ┆   ┆ dio        ┆ ---        ┆ ---      ┆ o         │
│ ---        ┆ str        ┆ str        ┆ i64  ┆   ┆ ---        ┆ i64        ┆ i64      ┆ ---       │
│ i64        ┆            ┆            ┆      ┆   ┆ i64        ┆            ┆          ┆ str       │
╞════════════╪════════════╪════════════╪══════╪═══╪════════════╪════════════╪══════════╪═══════════╡
│ 5          ┆ Computació ┆ En línea   ┆ 28   ┆ … ┆ 17         ┆ 67         ┆ 1        ┆ Las expli │
│            ┆ n          ┆            ┆      ┆   ┆            ┆            ┆          ┆ caciones  │
│            ┆            ┆            ┆      ┆   ┆            ┆            ┆          ┆ son       │
│            ┆            ┆            ┆      ┆   ┆            ┆            ┆          ┆ claras y… │
│ 8          ┆ Computació ┆ Presencial ┆ 40   ┆ … ┆ 20         ┆ 93         ┆ 1        ┆ Comprendo │
│            ┆ n          ┆            ┆      ┆   ┆            ┆            ┆          ┆ las activ │
│            ┆            ┆            ┆      ┆   ┆            ┆            ┆          ┆ idades y  │
│            ┆            ┆            ┆      ┆   ┆            ┆            ┆          ┆ di…       │
│ 13         ┆ Tecnología ┆ Presencial ┆ 42   ┆ … ┆ 11         ┆ 98         ┆ 1        ┆ Estudio   │
│            ┆ s de la    ┆            ┆      ┆   ┆            ┆            ┆          ┆ con regul │
│            ┆ Informació ┆            ┆      ┆   ┆            ┆            ┆          ┆ aridad y  │
│            ┆ n          ┆            ┆      ┆   ┆            ┆            ┆          ┆ me a…     │
│ 18         ┆ Tecnología ┆ Presencial ┆ 31   ┆ … ┆ 20         ┆ 69         ┆ 1        ┆ Las expli │
│            ┆ s de la    ┆            ┆      ┆   ┆            ┆            ┆          ┆ caciones  │
│            ┆ Informació ┆            ┆      ┆   ┆            ┆            ┆          ┆ son       │
│            ┆ n          ┆            ┆      ┆   ┆            ┆            ┆          ┆ claras y… │
│ 21         ┆ Tecnología ┆ En línea   ┆ 40   ┆ … ┆ 18         ┆ 52         ┆ 1        ┆ Me siento │
│            ┆ s de la    ┆            ┆      ┆   ┆            ┆            ┆          ┆ motivado  │
│            ┆ Informació ┆            ┆      ┆   ┆            ┆            ┆          ┆ y         │
│            ┆ n          ┆            ┆      ┆   ┆            ┆            ┆          ┆ organizo  │
│            ┆            ┆            ┆      ┆   ┆            ┆            ┆          ┆ …         │
│ …          ┆ …          ┆ …          ┆ …    ┆ … ┆ …          ┆ …          ┆ …        ┆ …         │
│ 84         ┆ Analítica  ┆ Presencial ┆ 43   ┆ … ┆ 17         ┆ 82         ┆ 1        ┆ Las expli │
│            ┆ de Datos   ┆            ┆      ┆   ┆            ┆            ┆          ┆ caciones  │
│            ┆            ┆            ┆      ┆   ┆            ┆            ┆          ┆ son       │
│            ┆            ┆            ┆      ┆   ┆            ┆            ┆          ┆ claras y… │
│ 87         ┆ Analítica  ┆ En línea   ┆ 19   ┆ … ┆ 12         ┆ 59         ┆ 1        ┆ Me siento │
│            ┆ de Datos   ┆            ┆      ┆   ┆            ┆            ┆          ┆ motivado  │
│            ┆            ┆            ┆      ┆   ┆            ┆            ┆          ┆ y         │
│            ┆            ┆            ┆      ┆   ┆            ┆            ┆          ┆ organizo  │
│            ┆            ┆            ┆      ┆   ┆            ┆            ┆          ┆ …         │
│ 97         ┆ Tecnología ┆ En línea   ┆ 31   ┆ … ┆ 15         ┆ 77         ┆ 1        ┆ Comprendo │
│            ┆ s de la    ┆            ┆      ┆   ┆            ┆            ┆          ┆ las activ │
│            ┆ Informació ┆            ┆      ┆   ┆            ┆            ┆          ┆ idades y  │
│            ┆ n          ┆            ┆      ┆   ┆            ┆            ┆          ┆ di…       │
│ 99         ┆ Tecnología ┆ En línea   ┆ 28   ┆ … ┆ 18         ┆ 100        ┆ 1        ┆ Comprendo │
│            ┆ s de la    ┆            ┆      ┆   ┆            ┆            ┆          ┆ las activ │
│            ┆ Informació ┆            ┆      ┆   ┆            ┆            ┆          ┆ idades y  │
│            ┆ n          ┆            ┆      ┆   ┆            ┆            ┆          ┆ di…       │
│ 100        ┆ Tecnología ┆ En línea   ┆ 23   ┆ … ┆ 20         ┆ 79         ┆ 1        ┆ Comprendo │
│            ┆ s de la    ┆            ┆      ┆   ┆            ┆            ┆          ┆ las activ │
│            ┆ Informació ┆            ┆      ┆   ┆            ┆            ┆          ┆ idades y  │
│            ┆ n          ┆            ┆      ┆   ┆            ┆            ┆          ┆ di…       │
└────────────┴────────────┴────────────┴──────┴───┴────────────┴────────────┴──────────┴───────────┘

In [12]:
mi_df.sort_values('nota_final', ascending=False).head()

,id_estudiante,carrera,modalidad,edad,nota_final,horas_estudio,asistencia,aprobado,comentario
60,61,Tecnologías de la Información,En línea,21,100.0,19,69,1.0,Las explicaciones son claras y puedo resolver ...
98,99,Tecnologías de la Información,En línea,28,100.0,18,100,1.0,Comprendo las actividades y disfruto practicar...
96,97,Tecnologías de la Información,En línea,31,100.0,15,77,1.0,Comprendo las actividades y disfruto practicar...
35,36,Redes,En línea,40,97.7,20,68,1.0,Estudio con regularidad y me ayuda practicar c...
66,67,Redes,Presencial,29,96.5,19,66,1.0,Estudio con regularidad y me ayuda practicar c...

In [13]:
df_polars.sort("nota_final", descending=True).head()

shape: (5, 9)
┌────────────┬────────────┬────────────┬──────┬───┬────────────┬────────────┬──────────┬───────────┐
│ id_estudia ┆ carrera    ┆ modalidad  ┆ edad ┆ … ┆ horas_estu ┆ asistencia ┆ aprobado ┆ comentari │
│ nte        ┆ ---        ┆ ---        ┆ ---  ┆   ┆ dio        ┆ ---        ┆ ---      ┆ o         │
│ ---        ┆ str        ┆ str        ┆ i64  ┆   ┆ ---        ┆ i64        ┆ i64      ┆ ---       │
│ i64        ┆            ┆            ┆      ┆   ┆ i64        ┆            ┆          ┆ str       │
╞════════════╪════════════╪════════════╪══════╪═══╪════════════╪════════════╪══════════╪═══════════╡
│ 10         ┆ Tecnología ┆ Presencial ┆ 38   ┆ … ┆ 19         ┆ 65         ┆ null     ┆ Comprendo │
│            ┆ s de la    ┆            ┆      ┆   ┆            ┆            ┆          ┆ algunos   │
│            ┆ Informació ┆            ┆      ┆   ┆            ┆            ┆          ┆ temas     │
│            ┆ n          ┆            ┆      ┆   ┆            ┆            ┆          ┆ pero n…   │
│ 25         ┆ Analítica  ┆ En línea   ┆ 20   ┆ … ┆ 12         ┆ 48         ┆ null     ┆ Comprendo │
│            ┆ de Datos   ┆            ┆      ┆   ┆            ┆            ┆          ┆ algunos   │
│            ┆            ┆            ┆      ┆   ┆            ┆            ┆          ┆ temas     │
│            ┆            ┆            ┆      ┆   ┆            ┆            ┆          ┆ pero n…   │
│ 94         ┆ Computació ┆ En línea   ┆ 25   ┆ … ┆ 3          ┆ 72         ┆ null     ┆ Los       │
│            ┆ n          ┆            ┆      ┆   ┆            ┆            ┆          ┆ ejemplos  │
│            ┆            ┆            ┆      ┆   ┆            ┆            ┆          ┆ me ayudan │
│            ┆            ┆            ┆      ┆   ┆            ┆            ┆          ┆ aunque …  │
│ 61         ┆ Tecnología ┆ En línea   ┆ 21   ┆ … ┆ 19         ┆ 69         ┆ 1        ┆ Las expli │
│            ┆ s de la    ┆            ┆      ┆   ┆            ┆            ┆          ┆ caciones  │
│            ┆ Informació ┆            ┆      ┆   ┆            ┆            ┆          ┆ son       │
│            ┆ n          ┆            ┆      ┆   ┆            ┆            ┆          ┆ claras y… │
│ 97         ┆ Tecnología ┆ En línea   ┆ 31   ┆ … ┆ 15         ┆ 77         ┆ 1        ┆ Comprendo │
│            ┆ s de la    ┆            ┆      ┆   ┆            ┆            ┆          ┆ las activ │
│            ┆ Informació ┆            ┆      ┆   ┆            ┆            ┆          ┆ idades y  │
│            ┆ n          ┆            ┆      ┆   ┆            ┆            ┆          ┆ di…       │
└────────────┴────────────┴────────────┴──────┴───┴────────────┴────────────┴──────────┴───────────┘

## 3. Agrupaciones y valores faltantes

In [14]:
mi_df.groupby('carrera')['nota_final'].mean()

carrera
Analítica de Datos               74.290000
Computación                      76.814286
Redes                            73.045455
Tecnologías de la Información    73.903704
Name: nota_final, dtype: float64

In [15]:
df_polars.group_by("carrera").agg(pl.col("nota_final").mean().alias("promedio")).sort("carrera")

shape: (4, 2)
┌───────────────────────────────┬───────────┐
│ carrera                       ┆ promedio  │
│ ---                           ┆ ---       │
│ str                           ┆ f64       │
╞═══════════════════════════════╪═══════════╡
│ Analítica de Datos            ┆ 74.29     │
│ Computación                   ┆ 76.814286 │
│ Redes                         ┆ 73.045455 │
│ Tecnologías de la Información ┆ 73.903704 │
└───────────────────────────────┴───────────┘

In [16]:
mi_df.isna().sum()

id_estudiante    0
carrera          0
modalidad        0
edad             0
nota_final       3
horas_estudio    0
asistencia       0
aprobado         3
comentario       0
dtype: int64

In [17]:
df_polars.null_count()

shape: (1, 9)
┌──────────────┬─────────┬───────────┬──────┬───┬─────────────┬────────────┬──────────┬────────────┐
│ id_estudiant ┆ carrera ┆ modalidad ┆ edad ┆ … ┆ horas_estud ┆ asistencia ┆ aprobado ┆ comentario │
│ e            ┆ ---     ┆ ---       ┆ ---  ┆   ┆ io          ┆ ---        ┆ ---      ┆ ---        │
│ ---          ┆ u32     ┆ u32       ┆ u32  ┆   ┆ ---         ┆ u32        ┆ u32      ┆ u32        │
│ u32          ┆         ┆           ┆      ┆   ┆ u32         ┆            ┆          ┆            │
╞══════════════╪═════════╪═══════════╪══════╪═══╪═════════════╪════════════╪══════════╪════════════╡
│ 0            ┆ 0       ┆ 0         ┆ 0    ┆ … ┆ 0           ┆ 0          ┆ 3        ┆ 0          │
└──────────────┴─────────┴───────────┴──────┴───┴─────────────┴────────────┴──────────┴────────────┘

## 4. Procesamiento diferido (*lazy*)
`scan_csv()` define una consulta sin materializar de inmediato todos los resultados. `collect()` la ejecuta.

In [18]:
consulta = (pl.scan_csv("data/rendimiento_10000.csv")
    .filter(pl.col("asistencia") >= 80)
    .group_by("carrera")
    .agg(pl.col("nota_final").mean().alias("promedio")))
consulta.collect()

shape: (4, 2)
┌───────────────────────────────┬───────────┐
│ carrera                       ┆ promedio  │
│ ---                           ┆ ---       │
│ str                           ┆ f64       │
╞═══════════════════════════════╪═══════════╡
│ Computación                   ┆ 82.539005 │
│ Analítica de Datos            ┆ 82.453417 │
│ Tecnologías de la Información ┆ 81.999437 │
│ Redes                         ┆ 82.146548 │
└───────────────────────────────┴───────────┘

## 5. Comparación exploratoria de tiempos
Una medición aislada de 10.000 filas **no demuestra** qué biblioteca es más rápida; incluimos los tiempos para familiarizarnos con la herramienta.

In [19]:
for n in (100, 1000, 10000):
    ruta = f"data/rendimiento_{n}.csv"
    inicio = perf_counter()
    a = pd.read_csv(ruta).groupby("carrera")["nota_final"].mean()
    t_pandas = perf_counter() - inicio
    inicio = perf_counter()
    b = pl.read_csv(ruta).group_by("carrera").agg(pl.col("nota_final").mean())
    t_polars = perf_counter() - inicio
    print(f"{n:>5} registros | Pandas: {t_pandas:.5f}s | Polars: {t_polars:.5f}s")

  100 registros | Pandas: 0.00195s | Polars: 0.00155s
 1000 registros | Pandas: 0.00457s | Polars: 0.00463s
10000 registros | Pandas: 0.01201s | Polars: 0.00523s